### ISSUE TITLE
Tilebundler fails running against OSM servers with bounds provided

### ISSUE THREAD

**Issue by ScottEvil** [ROGUE-JCTD/django-tilebundler#9]
If you give Tilebundler bounds when generating tiles using an OSM server (see osm-tileset-chef-repo), then you get the following exception:

{"error_message": "invalid configuration", "traceback": "Traceback (most recent call last):\n\n  File \"/var/lib/geonode/local/lib/python2.7/site-packages/tastypie/resources.py\", line 195, in wrapper\n    response = callback(request, _args, *_kwargs)\n\n  File \"/var/lib/geonode/local/lib/python2.7/site-packages/tilebundler/api.py\", line 75, in generate\n    return self.create_response(request, tileset.generate())\n\n  File \"/var/lib/geonode/local/lib/python2.7/site-packages/tilebundler/models.py\", line 63, in generate\n    pid = helpers.seed_process_spawn(self)\n\n  File \"/var/lib/geonode/local/lib/python2.7/site-packages/tilebundler/helpers.py\", line 333, in seed_process_spawn\n    mapproxy_conf, seed_conf = generate_confs(tileset)\n\n  File \"/var/lib/geonode/local/lib/python2.7/site-packages/tilebundler/helpers.py\", line 197, in generate_confs\n    raise SeedConfigurationError('invalid configuration')\n\nSeedConfigurationError: invalid configuration\n"}

With no bounds, the command works.

**Comment by smesdaghi** [comment]
This was already fixed in the latest one when tested.
